name: build

on:
  workflow_dispatch: 

jobs:
  build:
    strategy:
      matrix:
        java: [ '8', '11']
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: adopt

      - run: mvn --batch-mode verify
